<a href="https://colab.research.google.com/github/brunod02/Challenge-Data-Science/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

### En este primer análisis, debes calcular el ingreso total de cada tienda. Sumando los valores de la columna Precio de cada conjunto de datos de la tienda para estimar los ingresos.

In [9]:
tienda['Precio'].sum()

np.float64(1150880400.0)

In [10]:
tienda2['Precio'].sum()

np.float64(1116343500.0)

In [11]:
tienda3['Precio'].sum()

np.float64(1098019600.0)

In [12]:
tienda4['Precio'].sum()

np.float64(1038375700.0)

# 2. Ventas por categoría

## En este debes calcular la cantidad de productos vendidos por categoría en cada tienda. La idea es agrupar los datos por categoría y contar el número de ventas de cada tipo, mostrando las categorías más populares de cada tienda.

In [13]:
tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [27]:
tienda['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [28]:
df_cat = tienda['Categoría del Producto'].value_counts()

In [31]:
df_cat = df_cat.head()

In [32]:
df_cat

Categoría del Producto
Muebles                 465
Electrónicos            448
Juguetes                324
Electrodomésticos       312
Deportes y diversión    284
Name: count, dtype: int64

In [37]:
df_ventas_categorias1 = df_cat.reset_index()
df_ventas_categorias1 = df_ventas_categorias1.rename(columns={'count': 'Cantidad de Ventas'})
display(df_ventas_categorias1)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 465
1           Electrónicos                 448
2               Juguetes                 324
3      Electrodomésticos                 312
4   Deportes y diversión                 284

In [35]:
tienda2['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: count, dtype: int64

In [39]:
tienda2_ventas = tienda2['Categoría del Producto'].value_counts()
tienda2 = tienda2_ventas.reset_index()
tienda2 = tienda2.rename(columns={'count': 'Cantidad de Ventas'})
display(tienda2)

    Categoría del Producto  Cantidad de Ventas
0                  Muebles                 442
1             Electrónicos                 422
2                 Juguetes                 313
3        Electrodomésticos                 305
4     Deportes y diversión                 275
5   Instrumentos musicales                 224
6                   Libros                 197
7  Artículos para el hogar                 181

In [42]:
df_ventas_categorias2 = tienda2.head()

In [44]:
df_ventas_categorias2

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 442
1           Electrónicos                 422
2               Juguetes                 313
3      Electrodomésticos                 305
4   Deportes y diversión                 275

In [51]:
tienda3['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    1
Electrónicos               1
Juguetes                   1
Electrodomésticos          1
Deportes y diversión       1
Libros                     1
Instrumentos musicales     1
Artículos para el hogar    1
Name: count, dtype: int64

In [49]:
tienda3_ventas = tienda3['Categoría del Producto'].value_counts()
tienda3 = tienda3_ventas.reset_index()
tienda3 = tienda3.rename(columns={'count': 'Cantidad de Ventas'})
tienda3

    Categoría del Producto  Cantidad de Ventas
0                  Muebles                   1
1             Electrónicos                   1
2                 Juguetes                   1
3        Electrodomésticos                   1
4     Deportes y diversión                   1
5                   Libros                   1
6   Instrumentos musicales                   1
7  Artículos para el hogar                   1

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda