<a href="https://colab.research.google.com/github/brunod02/Challenge-Data-Science/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [84]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tiendas2 = pd.read_csv(url2)
tiendas3 = pd.read_csv(url3)
tiendas4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

### En este primer análisis, debes calcular el ingreso total de cada tienda. Sumando los valores de la columna Precio de cada conjunto de datos de la tienda para estimar los ingresos.

In [ ]:
tienda['Precio'].sum()

np.float64(1150880400.0)

In [ ]:
tiendas2['Precio'].sum()

np.float64(1116343500.0)

In [ ]:
tienda3['Precio'].sum()

np.float64(1098019600.0)

In [ ]:
tienda4['Precio'].sum()

np.float64(1038375700.0)

# 2. Ventas por categoría

## En este debes calcular la cantidad de productos vendidos por categoría en cada tienda. La idea es agrupar los datos por categoría y contar el número de ventas de cada tipo, mostrando las categorías más populares de cada tienda.

In [ ]:
tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [ ]:
tienda['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [ ]:
ventas_filtradas = df_ventas_categorias1[df_ventas_categorias1['Cantidad de Ventas'] > 250]

In [ ]:
df_cat = tienda['Categoría del Producto'].value_counts()

In [ ]:
ventas_filtradas = df_cat

In [ ]:
df_ventas_categorias1 = ventas_filtradas

In [ ]:
df_ventas_categorias1 = df_cat.reset_index()
df_ventas_categorias1 = df_ventas_categorias1.rename(columns={'count': 'Cantidad de Ventas'})
df_ventas_categorias = df_ventas_categorias1[df_ventas_categorias1['Cantidad de Ventas'] > 250]
display(df_ventas_categorias)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 465
1           Electrónicos                 448
2               Juguetes                 324
3      Electrodomésticos                 312
4   Deportes y diversión                 284

In [ ]:
tiendas2.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

In [ ]:
tienda2_ventas = tiendas2['Categoría del Producto'].value_counts()
tienda2 = tienda2_ventas.reset_index()
tienda2 = tienda2.rename(columns={'count': 'Cantidad de Ventas'})
tienda2 = tienda2[tienda2['Cantidad de Ventas'] > 250]
display(tienda2)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 442
1           Electrónicos                 422
2               Juguetes                 313
3      Electrodomésticos                 305
4   Deportes y diversión                 275

In [ ]:
df_ventas_categorias2 = tienda2

In [ ]:
df_ventas_categorias2

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 442
1           Electrónicos                 422
2               Juguetes                 313
3      Electrodomésticos                 305
4   Deportes y diversión                 275

In [73]:
tiendas3['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Instrumentos musicales     177
Artículos para el hogar    177
Name: count, dtype: int64

In [75]:
tienda3_ventas = tiendas3['Categoría del Producto'].value_counts()
tienda3 = tienda3_ventas.reset_index()
tienda3 = tienda3.rename(columns={'count': 'Cantidad de Ventas'})
tienda3 = tienda3[tienda3['Cantidad de Ventas'] > 250]
display(tienda3)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 499
1           Electrónicos                 451
2               Juguetes                 315
3      Electrodomésticos                 278
4   Deportes y diversión                 277

In [78]:
df_ventas_categorias3 = tienda3
display(df_ventas_categorias3)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 499
1           Electrónicos                 451
2               Juguetes                 315
3      Electrodomésticos                 278
4   Deportes y diversión                 277

In [85]:
tiendas4['Categoría del Producto'].value_counts()

Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: count, dtype: int64

In [88]:
tiendas4_ventas = tiendas4['Categoría del Producto'].value_counts()
tienda4 = tiendas4_ventas.reset_index()
tienda4 = tienda4.rename(columns={'count': 'Cantidad de Ventas'})
tienda4 = tienda4[tienda4['Cantidad de Ventas'] > 250]
display(tienda4)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 480
1           Electrónicos                 451
2               Juguetes                 338
3   Deportes y diversión                 277
4      Electrodomésticos                 254

In [89]:
df_ventas_categorias4 = tienda4
display(df_ventas_categorias4)

  Categoría del Producto  Cantidad de Ventas
0                Muebles                 480
1           Electrónicos                 451
2               Juguetes                 338
3   Deportes y diversión                 277
4      Electrodomésticos                 254

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda